### ISSUE TITLE
誰がどのプルリクをレビューするのかわからなくなる

### ISSUE THREAD

**Issue by rnitame** [sota1235/hubot-reviewer-choice#10]
# 概要

実装した人が `hubot choice $review` をしてお願いしたものの、レビュアーは他のことをしていて時間が経つと、担当のプルリクを忘れてしまうことがある。
# 解決案

`hubot choice reviewer list` のようなコマンドで確認できるようにする。出力内容は以下の様なイメージ

```
hubot choice reviewer list 

rnitame -> https://github.com/sota1235/hubot-reviewer-choice/pull/xxx
・
・
・
```
# その他

うざくなければ、30分おきくらいに `hubot choice reviewer list` を自動的に実行したい。個人個人が叩くと溜まっているレビュー数が多い時に外の会話が流れてしまうので。。

**Comment by sota1235** [comment]
なるほど～
もし実装するとしたら
- 会話中に出てくる一番最後の`github.com`の含まれたURLを保持する
- choiceする
- choiceの当選者にURLをセットしておく

あたりが簡単かなぁ。
でもこれだといつリストから消すのか問題とレビュアー選び以外の場面(司会選びとか)でどう処理するか問題があるので若干難しいね。あとはchoiceし直しとか。
他にうまい方法はないだろうか・・・

**Comment by rnitame** [comment]
あー…
hubot っていまいちわかってないのですが、情報貯めておけるものってないんですか？

情報貯めておいてそれをごにょごにょすればと思いましたが `hubot choice $review` がそもそも review に入れてる情報を呼んでる…？

**Comment by sota1235** [comment]
情報をためる方法はあるよ！
`hubot choice $hoge`はあらかじめ定義されたグループからランダムに選ぶような感じになってます！

いろいろ考えたけどこのnpmに機能含めるより`hubot assign`みたいな汎用的なhubot scriptを別npmで作って作ったほうがいいかもと思いついた。
`hubot assign sugiuras https://github.com/sota1235/hubot-reviewer-choice/issues/10`ってすると`hubot assign tasks`ってした時に自分にアサインされてるタスク(要するに文字列)が出てくるとか。
その時に下みたいな感じでIDとペアで出てきて、`hubot assign 1 done`とかやるとタスク消化したことになるとか。

イメージ。

``` shell
$ hubot assign sugiuras https://github.com/sota1235/hubot-reviewer-choice/issues/10
hubot > @sugiruas "https://github.com/sota1235/hubot-reviewer-choice/issues/10"をやってね

$ hubot assign list
hubot > @sugiuras 今は1個タスクがあるよ
hubot > 1 https://github.com/sota1235/hubot-reviewer-choice/issues/10

$ hubot assign 1 done (hubot assign done 1でもよさそう)
hubot > 1番目のタスクが終わったんだね！お疲れ！
hubot > 残りのタスクは0個だよ！

$ hubot assign list
hubot > @sugiuras 今は何もタスクないよ
```

**Comment by sota1235** [comment]
http://qiita.com/s-kiriki/items/4b38af4ebd05bad70eb7
https://www.npmjs.com/package/hubot-assign-pr

自動アサインってアプローチを取ってる人が多いけど個人的には操作がなるべくシンプルで汎用的な方が使いやすいと思うんよなぁ

**Comment by rnitame** [comment]
> 自動アサインってアプローチを取ってる人が多いけど個人的には操作がなるべくシンプルで汎用的な方が使いやすいと思うんよなぁ

完全に同意です。

> $ hubot assign sugiuras https://github.com/sota1235/hubot-reviewer-choice/issues/10

sugiuras のところは `hubot choice` したものが来るイメージですよね？

`hubot assign` とても良いと思うのでもう少し考えたいです :+1:

**Comment by sota1235** [comment]
`hubot choice`したものを取るには何かしらの形で履歴を取らなきゃいけないんよなぁ
データを永続化する時はKVSに保存するから例えば
- `hubot choice`の履歴をroomごとにとっておく(直近1件でいい)
- `hubot assign`する際、履歴があればその人にアサインする

とか？ただコマンドにあまり暗黙の仕様を含めたくないという葛藤。。。

**Comment by sota1235** [comment]
勝手にアサインするのでなく、リコメンドするくらいであればいいのかな

**Comment by sota1235** [comment]
https://github.com/sota1235/hubot-assign
見切り発車で作った

**Comment by rnitame** [comment]
なるほど
リコメンドで良いかもです！あとは運用でカバーできるかと

**Comment by sota1235** [comment]
だいたいできたのでclose

https://github.com/sota1235/hubot-assign/releases/tag/1.0.0
